controller_manager:
  ros__parameters:
    update_rate: 100

    adaptive_controller:
      type: adaptive_controllers/AdaptiveStateFeedbackController

      dof: 2
      joints: [joint0, joint1]

      # 關掉插件可跑最小回授；要自適應就打開
      enable_plugins: true
      # 在 MRAC 與 L1 之間切換：
      # adaptive_type: adaptive_controllers/MRACLaw
      adaptive_type: adaptive_controllers/L1Law

      # 不給 A/B/C/K 時，控制器會自動用 2nd-order canonical（A=[0 I;0 0], B=[0;I], C=[I 0]）
      # 如需自定，使用 *_data 一維 row-major（尺寸依 dof 推算）

      # 命令上下限（逐關節）
      u_min: [-10.0, -10.0]
      u_max: [ 10.0,  10.0]

      # 初始參考
      r0: [0.0, 0.0]

      # MRAC/L1 參數（控制器會轉交給插件）
      mrac.gamma: 5.0
      mrac.sigma: 0.01
      mrac.theta_max: 50.0
      l1.alpha: 20.0
