controller_manager:
  ros__parameters:
    update_rate: 100

    adaptive_controller:
      type: adaptive_controllers/AdaptiveStateFeedbackController

      # 多關節設定
      dof: 2
      joints: [joint0, joint1]

      # 先關閉 plugin（CI/測試友善）；示範時可開啟
      enable_plugins: false
      observer_type: adaptive_controllers/LuenbergerObserver
      adaptive_type: adaptive_controllers/MRACLaw

      # 不提供 A/B/C/K 時，控制器會自動使用 2nd-order canonical：
      # A=[0 I; 0 0], B=[0; I], C=[I 0]，K 預設 0
      # 若你要自定，可用 *_data（一維、row-major）給尺寸：
      # A_data: [ ... size = (2n)*(2n) ... ]
      # B_data: [ ... size = (2n)*n ... ]
      # C_data: [ ... size = n*(2n) ... ]
      # K_data: [ ... size = n*(2n) ... ]

      # 指令上下限
      u_min: [-10.0, -10.0]
      u_max: [ 10.0,  10.0]

      # 初始參考
      r0: [0.0, 0.0]
