controller_manager:
  ros__parameters:
    update_rate: 100

    adaptive_controller:
      type: adaptive_controllers/AdaptiveStateFeedbackController

      # 多關節設定（可改）
      dof: 1
      joints: [joint0]

      # 啟用/停用 plugin 載入（CI/測試建議先 false）
      enable_plugins: false
      observer_type: adaptive_controllers/LuenbergerObserver
      adaptive_type: adaptive_controllers/MRACLaw

      # A/B/C/K 皆以 row-major vector（*_data）提供，尺寸取決於 dof（此例 1x1）
      A_data: [0.0]
      B_data: [1.0]
      C_data: [1.0]
      K_data: [0.0]

      # 命令上下限（逐關節）
      u_min: [-10.0]
      u_max: [ 10.0]

      # 初始參考
      r0: [0.0]
