name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions
          rosdep update || true
          rosdep install --from-paths . --ignore-src -r -y || true
      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+
      - name: Test
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose
