name: Format
on:
  pull_request:
  push:

jobs:
  ament_uncrustify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install ament_uncrustify + uncrustify
        run: |
          sudo apt-get update
          sudo apt-get install -y ros-humble-ament-uncrustify uncrustify

      - name: Locate ament_uncrustify config
        id: cfg
        run: |
          set -e
          source /opt/ros/humble/setup.bash
          PREFIX="$(ros2 pkg prefix ament_uncrustify)"
          CANDIDATE="$PREFIX/share/ament_uncrustify/configuration/ament_code_style.cfg"
          echo "Trying: $CANDIDATE"
          if [ -f "$CANDIDATE" ]; then
            echo "cfg=$CANDIDATE" >> $GITHUB_OUTPUT
          else
            echo "::warning::Default cfg not found, listing dir for debug:"
            ls -la "$PREFIX/share/ament_uncrustify/configuration" || true
            # 後備：沒有就改用 ament_uncrustify 的預設（不指定 -c）
            echo "cfg=" >> $GITHUB_OUTPUT
          fi

      - name: Check formatting (reformat then diff)
        run: |
          set -e
          source /opt/ros/humble/setup.bash
          FILES="$(git ls-files | grep -E '\.(c|cc|cpp|cxx|h|hh|hpp|hxx)$' || true)"
          if [ -z "$FILES" ]; then
            echo "No C/C++ files to format."
            exit 0
          fi
          CFG="${{ steps.cfg.outputs.cfg }}"
          if [ -n "$CFG" ]; then
            ament_uncrustify -c "$CFG" --reformat $FILES
          else
            echo "::notice::Using ament_uncrustify default config (no -c)."
            ament_uncrustify --reformat $FILES
          fi
          git diff --exit-code
