name: Format

on:
  pull_request:
  push:

jobs:
  ament_uncrustify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install ament_uncrustify
        run: |
          sudo apt-get update
          sudo apt-get install -y ros-humble-ament-uncrustify

      - name: Locate uncrustify.cfg
        id: cfg
        run: |
          source /opt/ros/humble/setup.bash
          PREFIX=$(ros2 pkg prefix ament_uncrustify)
          echo "cfg=$PREFIX/share/ament_uncrustify/configuration/uncrustify.cfg" >> $GITHUB_OUTPUT

      - name: Check formatting (reformat in-place, then diff)
        run: |
          source /opt/ros/humble/setup.bash
          CFG="${{ steps.cfg.outputs.cfg }}"
          # 僅針對被 Git 追蹤的 C/C++ 檔案
          FILES=$(git ls-files | grep -E '\.(c|cc|cpp|h|hpp)$' || true)
          if [ -z "$FILES" ]; then
            echo "No C/C++ files to format."
            exit 0
          fi
          ament_uncrustify -c "$CFG" --reformat $FILES
          # 有變更就 fail，讓你在 PR/commit 看 diff
          git diff --exit-code
